# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "34c4d8e95ef5450d6411344ea4c44d18"
name = "Bakeshop OS"
application_url = "https://connector.bakeshop.digital"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_orders,read_products,read_discounts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://connector.bakeshop.digital/auth/callback",
  "https://connector.bakeshop.digital/auth/shopify/callback",
  "https://connector.bakeshop.digital/api/auth/callback",
]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = ["shop/redact"]

[pos]
embedded = false
